name: Build

on:
  push:
    pull_request: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Setting up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Installing packages
        run: |
          cd resources
          npm i
      - name: Running test suite
        run: |
          npm test
