name: Build

on:
 pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Setting up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Installing NPM packages
        run: |
          npm i
          cd resources
          npm i
          cd ../
          npm i aws-cdk --global
      - name: CDK Deploy
        run: cdk deploy
